image: node:10

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
  - node_modules/

stages:
  - build
  - unit_test
  - dev_deploy
  - integration_test
  - uat_deploy

build:
  stage: build
  script:
    - npm install
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

unit-test:
  stage: unit_test
  script:
    - npm run unit-tests
  only:
    - master
  cache:
    paths:
      - test_output/coverage/
  artifacts:
    paths:
      - test_output/coverage/
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: test_output/coverage/cobertura-coverage.xml

dev-deploy:
  stage: dev_deploy
  before_script:
    - npm install serverless@1.83.3
  script:
    - npm run dev-deploy
  environment:
    name: dev
  only:
    - master

integration-test:
  stage: integration_test
  before_script:
    - npm install -g ask-cli
  script:
    - ./deploy.sh
    - npm run smapi-tests
  only:
    - master

uat-deploy:
  stage: uat_deploy
  before_script:
    - npm install serverless@1.83.3
  script:
    - npm run uat-deploy
  environment:
    name: uat
  only:
    - master