image: node:14

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
  - node_modules/

stages:
  - build
  - unit_test
  - dev_deploy

build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

unit-test:
  stage: unit_test
  script:
    - npm run unit-tests

dev-deploy:
  stage: dev_deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless@1.83.3
  script:
    - serverless deploy -s dev
  environment:
    name: dev
  only:
    - master
