image: node:10

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
  - node_modules/

stages:
  - build
  - unit_test
  - dev_deploy
  - integration_test
  - uat_deploy

build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

unit-test:
  stage: unit_test
  script:
    - npm run unit-tests
  only:
    - master
  artifacts:
    paths:
      - test/test_output/coverage/lcov-report/index.html
    reports:
      junit: test/test_output/coverage/lcov-report/index.html

dev-deploy:
  stage: dev_deploy
  before_script:
    - npm install serverless@1.83.3
  script:
    - npm run dev-deploy
  environment:
    name: dev
  only:
    - master

integration-test:
  stage: integration_test
  before_script:
    - npm install -g ask-cli
  script:
    - npm run smapi-tests
  only:
    - master

# uat-deploy:
#   stage: uat_deploy
#   before_script:
#     - npm install serverless@1.83.3
#   script:
#     - npm run uat-deploy
#   environment:
#     name: uat
#   only:
#     - master