environment:
  STAGE: ${self:provider.stage}
  WARMUP_RULE_LABEL: "melvin-alexa-intent-handlers-${self:provider.stage}-warmup_service"
  MELVIN_WELCOME_GREETING: "Welcome to Melvin development version."
  MELVIN_APP_NAME: "Melvin develop"
  DYNAMODB_TABLE_USER_UTTERANCE: melvin-user-utterance-${self:provider.stage}
  DYNAMODB_TABLE_USER_SESSION: melvin-user-session-${self:provider.stage}
  SQS_IRS: 073302257160:melvin-sqs-irs-${self:provider.stage}
  SQS_WARMUP: 073302257160:melvin-sqs-warmup-${self:provider.stage}
  MELVIN_EXPLORER_ENDPOINT: "https://api.dev.melvin.pittlabgenomics.com/v0.1"
  MELVIN_EXPLORER_INVOKE_ROLE: "arn:aws:iam::073302257160:role/melvin-explorer-dev-api-invoke"
  MELVIN_EXPLORER_REGION: "ap-southeast-1"
  OOV_MAPPER_ENDPOINT: "https://api.dev.oovm.pittlabgenomics.com/v0.1/oov-ml-mapper-dev"
  OOV_MAPPER_INVOKE_ROLE: "arn:aws:iam::073302257160:role/oov-mapper-dev-api-invoke"
  OOV_MAPPER_REGION: "ap-southeast-1"

alexa:
  appId: amzn1.ask.skill.76bde827-301f-478d-af1a-c7241f046388
