environment:
  STAGE: ${self:provider.stage}
  REGION: ${self:provider.region}
  AWS_ACCOUNT_ID: ${aws:accountId}
  MELVIN_WELCOME_GREETING: "Welcome to Melvin development version"
  MELVIN_APP_NAME: "Melvin develop"
  DYNAMODB_TABLE_USER_UTTERANCE: melvin-user-utterance-${self:provider.stage}
  DYNAMODB_TABLE_USER_SESSION: melvin-user-session-${self:provider.stage}
  DYNAMODB_TABLE_USER_PREFERENCE: melvin-user-preference-${self:provider.stage}
  DYNAMODB_TABLE_VOICE_RECORDER: melvin-recorder-utterance-${self:provider.stage}
  SQS_IRS: melvin-sqs-irs-${self:provider.stage}
  SES_IDENTITY: identity/melvin.pittlabgenomics.com
  SQS_WARMUP: melvin-sqs-warmup-${self:provider.stage}
  MELVIN_EXPLORER_ENDPOINT: "https://api.dev.melvin.pittlabgenomics.com/v0.1"
  MELVIN_API_INVOKE_ROLE: "arn:aws:iam::${aws:accountId}:role/melvin-${self:provider.stage}-skill-intent-handler-role"
  MELVIN_EXPLORER_REGION: "ap-southeast-1"
  OOV_MAPPER_ENDPOINT: "https://api.dev.oovm.pittlabgenomics.com/v0.1"
  OOV_MAPPER_REGION: "ap-southeast-1"
  PROFILE_INFO_ENDPOINT: "https://api.amazon.com/user/profile"
  WARMUP_SERVICE_ENABLED: true
  WARMUP_EVENT_RULE_NAME: "melvin-warmup-event-rule-${self:provider.stage}"
  WARMUP_EVENT_SCHEDULE_RATE: 1 minute
  WARMUP_EVENT_DELAY_MAX: 60
  WARMUP_EVENT_COUNT: 3
  WARMUP_PARALLEL_REQUEST_COUNT: 6
alexa:
  appId: amzn1.ask.skill.76bde827-301f-478d-af1a-c7241f046388
