environment:
  MELVIN_WELCOME_GREETING: "Welcome to Melvin development version."
  MELVIN_APP_NAME: "Melvin develop"
  DYNAMODB_TABLE_USER_UTTERANCE: melvin-user-utterance-${self:provider.stage}
  DYNAMODB_TABLE_USER_SESSION: melvin-user-session-${self:provider.stage}
  SQS_IRS: 073302257160:melvin-sqs-irs-${self:provider.stage}
  SQS_WARMUP: 073302257160:melvin-sqs-warmup-${self:provider.stage}
  MELVIN_EXPLORER_ENDPOINT: "https://api.dev.melvin.pittlabgenomics.com/v0.1"
  OOV_MAPPER_ENDPOINT: "https://api.uat.oovm-fg.pittlabgenomics.com/v0.0.1/"

alexa:
  appId: amzn1.ask.skill.76bde827-301f-478d-af1a-c7241f046388
