environment:
  MELVIN_WELCOME_GREETING: "Welcome to Melvin."
  MELVIN_APP_NAME: "Melvin"
  DYNAMODB_TABLE_ENTITY_QUERIES: ${self:service}-entity-queries-${self:provider.stage}
  MELVIN_EXPLORER_ENDPOINT: "https://api.uat.melvin.pittlabgenomics.com/v0.1"
  OOV_MAPPER_ENDPOINT: "https://api.uat.oovm.pittlabgenomics.com/v0.1"

alexa:
  appId: amzn1.ask.skill.b4093683-e7de-4469-8fa4-453711c5ee2d
