environment:
  STAGE: ${self:provider.stage}
  WARMUP_EVENT_RULE_NAME: "melvin-warmup-event-rule-${self:provider.stage}"
  MELVIN_WELCOME_GREETING: "Welcome to Melvin."
  MELVIN_APP_NAME: "Melvin"
  DYNAMODB_TABLE_USER_UTTERANCE: melvin-user-utterance-${self:provider.stage}
  DYNAMODB_TABLE_USER_SESSION: melvin-user-session-${self:provider.stage}
  DYNAMODB_TABLE_USER_PREFERENCE: melvin-user-preference-${self:provider.stage}
  DYNAMODB_TABLE_VOICE_RECORDER: melvin-voice-recorder
  SQS_IRS: 073302257160:melvin-sqs-irs-${self:provider.stage}
  SQS_WARMUP: 073302257160:melvin-sqs-warmup-${self:provider.stage}
  MELVIN_EXPLORER_ENDPOINT: "https://api.uat.melvin.pittlabgenomics.com/v0.1"
  MELVIN_API_INVOKE_ROLE: "arn:aws:iam::073302257160:role/melvin-${self:provider.stage}-skill-intent-handler-role"
  MELVIN_EXPLORER_REGION: "ap-southeast-1"
  OOV_MAPPER_ENDPOINT: "https://api.uat.oovm.pittlabgenomics.com/v0.1"
  OOV_MAPPER_REGION: "ap-southeast-1"
  WARMUP_SERVICE_ENABLED: true
  WARMUP_EVENT_SCHEDULE_RATE: 1 minute
  WARMUP_EVENT_COUNT: 5
alexa:
  appId: amzn1.ask.skill.b4093683-e7de-4469-8fa4-453711c5ee2d
